from django.urls import path
from . import views
from django.contrib.auth import views as authViews
from blog import views as blog_views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('blog/', views.blog_view, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail_view, name='blog_detail'),
    path('profile/signup_doctor/', views.signup_doctor_view, name="signup_doctor"),
    path('profile/logout/', views.logout_view, name='logout'),
    path('profile/login/', views.login_view, name='login'),
    path('profile/signup_user/', views.signup_user_view, name="signup_user"),
    path('profile/info/', views.profile_page_view, name='user_profile'),
    path('profile/main/', views.profile_page_view, name='user_profile_main'),
    path('profile/recomend/', views.profile_page_view, name='user_profile_recomend'),
    path('profile/grafik/', views.profile_page_view, name='user_profile_grafik'),
    path('profile/consalt_user/', views.profile_page_view, name='user_profile_consalt_user'),
    path('profile/contact_user/', views.profile_page_view, name='user_profile_contact_user'),
    path('profile/settings/', views.profile_page_view, name='user_profile_settings'),
    path('profile/videos/', views.profile_page_view, name='user_profile_videos'),
    path('profile/articles/', views.profile_page_view, name='user_profile_articles'),
    path('profile/reviews/', views.profile_page_view, name='user_profile_reviews'),
    path('profile/consalt_doctor/', views.get_task_view, name='user_profile_consalt_doctor'),
    path('profile/article_edit/<slug:slug>/', blog_views.edit_article_view, name='edit_article'),
    path('profile/article_add/', blog_views.add_article_view, name='add_article'),
    path('profile/article_remove/<slug:slug>/', blog_views.remove_article_view, name='remove_article'),
    path('profile/article_remove_success/<slug:slug>/', blog_views.article_remove_success, name='article_remove_success'),
    path('profile/save_article_success/', blog_views.save_article_success, name='save_article_success'),
    path('profile/save_main_data/', views.save_main_data, name='save_main_data'),
    path('profile/save_doctor_data/', views.save_doctor_data, name='save_doctor_data'),
    path('profile/change_user_pass/', views.change_user_pass, name='change_user_pass'),
    path('profile/save_support_message/', views.save_support_message, name='save_support_message'),
    path('profile/save_user_doc/', views.save_user_doc, name='save_user_doc'),
    path('profile/save_review_view/', views.save_review_view, name='save_review_view'),
    path('profile/remove_user_doc/', views.remove_user_doc, name='remove_user_doc'),
    path('profile/save_data_success/', views.save_data_success, name='save_data_success'),
    path('profile/save_consalt_success/', views.save_consalt_success, name='save_consalt_success'),
    path('profile/save_review_success/', views.save_review_success, name='save_review_success'),
    path('profile/save_verification_success/', views.save_verification_success, name='save_verification_success'),
    path('profile/send_file_for_verified/', views.send_file_for_verified, name='send_file_for_verified'),
    path('profile/pass_reset/', authViews.PasswordResetView.as_view(template_name='profile/password_reset.html', email_template_name='profile/password_reset_email.html'), name="pass_reset"),
    path('profile/password_reset_complete/', authViews.PasswordResetCompleteView.as_view(template_name='profile/password_reset_complete.html'), name="password_reset_complete"),
    path('profile/password_reset_confirm/<uidb64>/<token>/', authViews.PasswordResetConfirmView.as_view(template_name='profile/password_reset_confirm.html'), name="password_reset_confirm"),
    path('profile/password_reset_done/', authViews.PasswordResetDoneView.as_view(template_name='profile/password_reset_done.html'), name="password_reset_done"),
]