# Generated by Django 3.1.4 on 2021-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('review', 'Рассмотрение'), ('success', 'Одобрено'), ('reject', 'Отказ'), ('archive', 'Архив')], max_length=11, null=True, verbose_name='Статус'),
        ),
    ]
