# Generated by Django 3.1.3 on 2020-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201126_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
