# Generated by Django 3.1.3 on 2020-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201126_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fio',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(max_length=100, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True, verbose_name='WhatsApp'),
        ),
    ]
