# Generated by Django 3.1.3 on 2020-11-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_auto_20201126_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=11, null=True, verbose_name='Пол')),
                ('usertype', models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], max_length=11, null=True, verbose_name='Тип')),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Изображение')),
                ('fio', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('whatsapp', models.CharField(max_length=100, null=True, verbose_name='WhatsApp')),
                ('skype', models.CharField(max_length=100, null=True, verbose_name='Skype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=11, null=True, verbose_name='Пол')),
                ('usertype', models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], max_length=11, null=True, verbose_name='Тип')),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Изображение')),
                ('fio', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('whatsapp', models.CharField(max_length=100, null=True, verbose_name='WhatsApp')),
                ('skype', models.CharField(max_length=100, null=True, verbose_name='Skype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
