# Generated by Django 3.1.3 on 2020-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20201126_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoctor',
            name='author',
            field=models.BooleanField(default=False, verbose_name='Я автор видеолекций'),
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='fullDoctor',
            field=models.BooleanField(default=False, verbose_name='Я врач и консультант'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='consultant',
            field=models.BooleanField(default=False, verbose_name='Я консультант'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='doctor',
            field=models.BooleanField(default=False, verbose_name='Я врач'),
        ),
    ]
