# Generated by Django 3.1.3 on 2020-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20201126_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoctor',
            name='patientChildren',
            field=models.BooleanField(default=False, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='patientGrown',
            field=models.BooleanField(default=False, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='specialty',
            field=models.CharField(max_length=100, null=True, verbose_name='Специализация'),
        ),
    ]
