# Generated by Django 3.1.3 on 2020-12-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20201126_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoctor',
            name='orgtype',
            field=models.CharField(choices=[('ur', 'Юридическое лицо'), ('fiz', 'Физическое лицо')], default=False, max_length=11, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='specialty',
            field=models.CharField(default=False, max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='city',
            field=models.CharField(default=False, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='fio',
            field=models.CharField(default=False, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default=False, max_length=11, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='skype',
            field=models.CharField(default=False, max_length=100, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='usertype',
            field=models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], default=False, max_length=11, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.CharField(default=False, max_length=100, verbose_name='WhatsApp'),
        ),
    ]
