# Generated by Django 3.1.3 on 2020-12-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20201203_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='avatar',
            field=models.ImageField(default=False, upload_to='images/users', verbose_name='Изображение'),
        ),
    ]
