# Generated by Django 3.1.3 on 2020-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20201203_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoctor',
            name='author',
            field=models.BooleanField(default='', verbose_name='Я автор видеолекций'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='consultant',
            field=models.BooleanField(default='', verbose_name='Я консультант'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='doctor',
            field=models.BooleanField(default='', verbose_name='Я врач'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='fullDoctor',
            field=models.BooleanField(default='', verbose_name='Я врач и консультант'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='orgtype',
            field=models.CharField(choices=[('ur', 'Юридическое лицо'), ('fiz', 'Физическое лицо')], default='', max_length=11, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='patientChildren',
            field=models.BooleanField(default='', verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='patientGrown',
            field=models.BooleanField(default='', verbose_name='Взрослые'),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='specialty',
            field=models.CharField(default='', max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='avatar',
            field=models.ImageField(upload_to='images/users', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='fio',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=11, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='skype',
            field=models.CharField(default='', max_length=100, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='usertype',
            field=models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], default='', max_length=11, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.CharField(default='', max_length=100, verbose_name='WhatsApp'),
        ),
    ]
