# Generated by Django 3.1.3 on 2020-12-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20201204_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/users', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='fio',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='', max_length=11, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='skype',
            field=models.CharField(default='', max_length=100, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.CharField(default='', max_length=100, verbose_name='WhatsApp'),
        ),
    ]
