# Generated by Django 3.1.3 on 2020-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_usermain_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermain',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('UTC +3', '(UTC +3) Москва, Санкт-Петербург, Воронеж, Казань'), ('UTC +7', '(UTC +7): Республика Алтай, Алтайский край, Новосибирская, Омская, Томская области')], max_length=11, verbose_name='Временная зона'),
        ),
    ]
