# Generated by Django 3.1.3 on 2020-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_auto_20201208_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация'),
        ),
    ]
