# Generated by Django 3.1.3 on 2020-12-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0028_auto_20201214_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipAssociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Членство в ассоциациях',
                'verbose_name_plural': 'Членство в ассоциациях',
            },
        ),
    ]
