# Generated by Django 3.1.3 on 2020-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0029_membershipassociations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipassociations',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
