# Generated by Django 3.1.3 on 2020-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0033_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ImageField(max_length=10, upload_to='')),
                ('user_name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Сообщение в службу поддержки',
                'verbose_name_plural': 'Сообщения в службу поддержки',
            },
        ),
    ]
