# Generated by Django 3.1.3 on 2020-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0034_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='user_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
