# Generated by Django 3.1.3 on 2020-12-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0036_auto_20201215_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone_name', models.CharField(blank=True, max_length=30)),
                ('time_zone_title', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Временные зоны',
                'verbose_name_plural': 'Временные зоны',
            },
        ),
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='experienceText',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Опыт работы'),
        ),
    ]
