# Generated by Django 3.1.3 on 2020-12-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0037_auto_20201216_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='time_zone_name',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='time_zone_title',
        ),
        migrations.AddField(
            model_name='timezone',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='timezone',
            name='title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='time_zone',
            field=models.CharField(blank=True, choices=[], max_length=2000, verbose_name='Временная зона'),
        ),
    ]
