# Generated by Django 3.1.3 on 2020-12-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0038_auto_20201216_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezone',
            old_name='name',
            new_name='time_zone_name',
        ),
        migrations.RenameField(
            model_name='timezone',
            old_name='title',
            new_name='time_zone_title',
        ),
    ]
