# Generated by Django 3.1.3 on 2020-12-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0039_auto_20201216_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezone',
            old_name='time_zone_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='timezone',
            old_name='time_zone_title',
            new_name='title',
        ),
    ]
