# Generated by Django 3.1.3 on 2020-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0040_auto_20201216_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('UTC +3', '(UTC +3) Москва, Санкт-Петербург, Воронеж, Казань'), ('UTC +7', '(UTC +7): Республика Алтай, Алтайский край, Новосибирская, Омская, Томская области')], max_length=2000, verbose_name='Временная зона'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
