# Generated by Django 3.1.3 on 2020-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0042_auto_20201216_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер телефона'),
        ),
    ]
