# Generated by Django 3.1.3 on 2020-12-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0044_auto_20201217_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associations',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.CharField(max_length=20, verbose_name='Года'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='skype',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=20, verbose_name='Года')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повышение квалификации',
                'verbose_name_plural': 'Повышение квалификации',
            },
        ),
    ]
