# Generated by Django 3.1.3 on 2020-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0045_auto_20201217_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoctor',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='userdoctor',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='userdoctor',
            name='fullDoctor',
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='meet_offline',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прием оффлайн'),
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='meet_online',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прием онлайн'),
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='meet_online_offline',
            field=models.BooleanField(blank=True, null=True, verbose_name='Прием онлайн и оффлайн'),
        ),
    ]
