# Generated by Django 3.1.3 on 2020-12-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0046_auto_20201218_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdoctor',
            old_name='patientChildren',
            new_name='patient_children',
        ),
        migrations.RenameField(
            model_name='userdoctor',
            old_name='patientGrown',
            new_name='patient_grown',
        ),
    ]
