# Generated by Django 3.1.3 on 2020-12-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0047_auto_20201218_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdoctor',
            old_name='experienceText',
            new_name='experience_text',
        ),
        migrations.RenameField(
            model_name='userdoctor',
            old_name='experienceYears',
            new_name='experience_years',
        ),
    ]
