# Generated by Django 3.1.3 on 2020-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0048_auto_20201218_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Список специальностей',
                'verbose_name_plural': 'Список специальностей',
            },
        ),
    ]
