# Generated by Django 3.1.4 on 2020-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0050_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoctor',
            name='verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аккаунт верифицирован'),
        ),
    ]
