# Generated by Django 3.1.4 on 2020-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0052_auto_20201222_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoctor',
            name='author',
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='experience_years',
            field=models.IntegerField(blank=True, max_length=2, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
