# Generated by Django 3.1.4 on 2020-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0053_auto_20201228_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermain',
            name='coords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Координаты'),
        ),
    ]
