# Generated by Django 3.1.4 on 2020-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0054_usermain_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermain',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usermain',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
