# Generated by Django 3.1.4 on 2020-12-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0055_auto_20201228_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoctor',
            name='experience_years',
            field=models.CharField(blank=True, max_length=2, verbose_name='Стаж'),
        ),
    ]
