# Generated by Django 3.1.4 on 2021-01-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0056_auto_20201228_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoctor',
            name='specialty',
        ),
    ]
