# Generated by Django 3.1.4 on 2021-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0060_specialtylist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoctor',
            name='meet_online_offline',
        ),
    ]
