# Generated by Django 3.1.4 on 2021-01-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('data', models.DateTimeField(blank=True, max_length=100, verbose_name='Дата и время')),
                ('doctor_id', models.TextField(blank=True, max_length=10, verbose_name='Доктор')),
                ('user_id', models.TextField(blank=True, max_length=10, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
    ]
