# Generated by Django 3.1.4 on 2021-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210107_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('data', models.DateField(blank=True, max_length=100, verbose_name='Дата')),
                ('time_start', models.TimeField(default='00:00:00', max_length=100, verbose_name='Время начало')),
                ('time_end', models.TimeField(default='00:00:00', max_length=100, verbose_name='Время конец')),
                ('doctor_id', models.IntegerField(blank=True, default=1, verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
    ]
