# Generated by Django 3.1.4 on 2021-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20210114_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='service_id',
            field=models.IntegerField(blank=True, default=1, verbose_name='Услуга'),
        ),
    ]
