# Generated by Django 3.1.4 on 2021-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_meeting_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default='00:00:00', max_length=100, verbose_name='Время конец'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default='00:00:00', max_length=100, verbose_name='Время начало'),
        ),
    ]
