# Generated by Django 3.1.4 on 2021-01-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sort_id',
            field=models.IntegerField(blank=True, default=1, verbose_name='Индекс сортитровки'),
        ),
    ]
