# Generated by Django 3.1.4 on 2021-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_meeting_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('work', 'В работе'), ('success', 'Выполнено'), ('reject', 'Отказ'), ('archive', 'Архив')], max_length=11, null=True, verbose_name='Статус'),
        ),
    ]
