# Generated by Django 3.1.4 on 2021-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_meeting_email_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email_notify',
            field=models.BooleanField(blank=True, default=0, verbose_name='Уведомление на почту'),
        ),
    ]
