# Generated by Django 3.1.4 on 2021-02-10 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_auto_20210204_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('doctor_id', models.IntegerField(blank=True, default=1, verbose_name='Доктор')),
                ('user_id', models.IntegerField(blank=True, default=1, verbose_name='Пациент')),
                ('star', models.IntegerField(blank=True, default=0, verbose_name='Рейтинг')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
